name: Build and Package

on: [push]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          if ('${{ startsWith(github.ref, 'refs/tags/') }}' -eq 'true') {
            dotnet publish -r win-x64 -c Release /p:Version=${{ github.ref_name }}
          } else {
            dotnet publish -r win-x64 -c Release
          }

      - name: Create zip artifact
        run: |
          Compress-Archive -Path .\bin\Release\net8.0\win-x64\publish\DOFConnect.dll -DestinationPath dofconnect -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dofconnect
          path: dofconnect.zip
          retention-days: 7

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: dofconnect

      - name: ls
        run: ls -alrt
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          generateReleaseNotes: true
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          allowUpdates: true
          artifacts: "dofconnect*"
          tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', github.sha) }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Latest' }}
